---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 241260191-Ug2xzTNUv5KveD3YfkZHumRFZKM3uWdLJDVGP6kP
:access_token_secret: vpmVJPuyTpxSrG6xdok4ITVGM1y94RjrYGpJzcmDVJWxq
